#!url=https://raw.githubusercontent.com/quocchienn/quocchien/refs/heads/Quocchien_Module/VSCO.sgmodule
#!name=Picsrat
#!desc=By: Quoc Chien

[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[MITM]
hostname = api.revenuecat.com, buy.itunes.apple.com, api.picsart.com, us-central1-alight-creative.cloudfunctions.net, api.adapty.io, carrotweather.herokuapp.com, lcs-mobile-cops.adobe.io, order.creativeappnow.com, api.mwm-users.com, us-central1-muslim-pro-app.cloudfunctions.net, api.gptkeyboard.app, prod.studysmarter.de, api.qonversion.io, api.blinkist.com, subscription.grammarly.com, api.esound.app, api.purchasely.io,

[Script]
http-response ^https://api\.revenuecat\.com/.+/(receipts$|subscribers/[^/]+$) script-path=https://N9dev-dev.github.io/SL/scripts/ARC.js, requires-body=true, timeout=5, tag=iSteal
http-response https://api-fra.vivacut.com/api/rest/commerce/integrate/vip/perform script-path=https://N9dev-dev.github.io/SL/scripts/VivaCut.js, requires-body=true, timeout=5, tag=VivaCut
http-request https://lcs-mobile-cops.adobe.io/mobiles/access_profile/v3 script-path=https://N9dev-dev.github.io/SL/scripts/Lightroom.js, requires-body=true, timeout=5, tag=Lightroom
http-request ^https://api.revenuecat.com/.+/(receipts$|subscribers/?(.*?)*$) script-path=https://N9dev-dev.github.io/SL/scripts/VSCO.js, requires-body=true, timeout=5, tag=VSCOr
http-request https://api.picsart.com/gw-v2/shop/subscription/apple/purchases script-path=https://N9dev-dev.github.io/SL/scripts/PicsArt.js, requires-body=true, timeout=5, tag=PicsArt
http-response https://us-central1-alight-creative.cloudfunctions.net/getAccountStatusAndLicenses script-path=https://N9dev-dev.github.io/SL/scripts/AlightMotion.js, requires-body=true, timeout=5, tag=Alight Motion
http-response api.sandbox.love/accounts/current script-path=https://N9dev-dev.github.io/SL/scripts/SandBox.js, requires-body=true, timeout=5, tag=Sandbox Pixel Art